// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: serverproto.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace RoomProto {

  /// <summary>Holder for reflection information generated from serverproto.proto</summary>
  public static partial class ServerprotoReflection {

    #region Descriptor
    /// <summary>File descriptor for serverproto.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServerprotoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFzZXJ2ZXJwcm90by5wcm90bxIJUm9vbVByb3RvIjIKDlRBY3Rvck1vdmVJ",
            "bmZvEg0KBWFuZ2xlGAEgASgDEhEKCWlzX21vdmluZxgCIAEoCCJdCgZUU2tp",
            "bGwSEgoKc2tpbGxfdHlwZRgBIAEoAxISCgpmaXJlX2FuZ2xlGAIgASgDEhYK",
            "DmZpcmVfYW5nbGVfbGVuGAMgASgDEhMKC2NoYXJnZV90aW1lGAQgASgDInwK",
            "CVRSb2xlSW5mbxIPCgdyb2xlX2lkGAEgASgJEg0KBWxldmVsGAIgASgFEgwK",
            "BG5hbWUYAyABKAkSFgoOcm9sZV9jb25maWdfaWQYBCABKAUSEAoIaXNfcmVh",
            "ZHkYBSABKAgSFwoPY29tbW9uX3NraWxsX2lkGAYgASgFIqQCCg1UUlBHUGxh",
            "eWVyQ21kEhAKCGFjdG9yX2lkGAEgASgJEg4KBmNtZF9pZBgCIAEoBRITCgtj",
            "cmVhdGVfdGltZRgDIAEoAxIaChJjcmVhdGVfZnJhbWVfY291bnQYBCABKAUS",
            "EwoLZnJhbWVfY291bnQYBSABKAUSEQoJY21kX2luZGV4GAYgASgFEiEKBnNr",
            "aWxscxgHIAMoCzIRLlJvb21Qcm90by5UU2tpbGwSJwoEbW92ZRgIIAEoCzIZ",
            "LlJvb21Qcm90by5UQWN0b3JNb3ZlSW5mbxIRCglwbGF5ZXJfaWQYCSABKAkS",
            "JwoJcm9sZV9pbmZvGAogASgLMhQuUm9vbVByb3RvLlRSb2xlSW5mbxIQCghj",
            "bWRfdHlwZRgLIAEoBWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::RoomProto.TActorMoveInfo), global::RoomProto.TActorMoveInfo.Parser, new[]{ "Angle", "IsMoving" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::RoomProto.TSkill), global::RoomProto.TSkill.Parser, new[]{ "SkillType", "FireAngle", "FireAngleLen", "ChargeTime" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::RoomProto.TRoleInfo), global::RoomProto.TRoleInfo.Parser, new[]{ "RoleId", "Level", "Name", "RoleConfigId", "IsReady", "CommonSkillId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::RoomProto.TRPGPlayerCmd), global::RoomProto.TRPGPlayerCmd.Parser, new[]{ "ActorId", "CmdId", "CreateTime", "CreateFrameCount", "FrameCount", "CmdIndex", "Skills", "Move", "PlayerId", "RoleInfo", "CmdType" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// 移动方向信息
  /// </summary>
  public sealed partial class TActorMoveInfo : pb::IMessage<TActorMoveInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TActorMoveInfo> _parser = new pb::MessageParser<TActorMoveInfo>(() => new TActorMoveInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<TActorMoveInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::RoomProto.ServerprotoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TActorMoveInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TActorMoveInfo(TActorMoveInfo other) : this() {
      angle_ = other.angle_;
      isMoving_ = other.isMoving_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TActorMoveInfo Clone() {
      return new TActorMoveInfo(this);
    }

    /// <summary>Field number for the "angle" field.</summary>
    public const int AngleFieldNumber = 1;
    private long angle_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Angle {
      get { return angle_; }
      set {
        angle_ = value;
      }
    }

    /// <summary>Field number for the "is_moving" field.</summary>
    public const int IsMovingFieldNumber = 2;
    private bool isMoving_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool IsMoving {
      get { return isMoving_; }
      set {
        isMoving_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as TActorMoveInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(TActorMoveInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Angle != other.Angle) return false;
      if (IsMoving != other.IsMoving) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Angle != 0L) hash ^= Angle.GetHashCode();
      if (IsMoving != false) hash ^= IsMoving.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Angle != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Angle);
      }
      if (IsMoving != false) {
        output.WriteRawTag(16);
        output.WriteBool(IsMoving);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Angle != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Angle);
      }
      if (IsMoving != false) {
        output.WriteRawTag(16);
        output.WriteBool(IsMoving);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Angle != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Angle);
      }
      if (IsMoving != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(TActorMoveInfo other) {
      if (other == null) {
        return;
      }
      if (other.Angle != 0L) {
        Angle = other.Angle;
      }
      if (other.IsMoving != false) {
        IsMoving = other.IsMoving;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Angle = input.ReadInt64();
            break;
          }
          case 16: {
            IsMoving = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Angle = input.ReadInt64();
            break;
          }
          case 16: {
            IsMoving = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class TSkill : pb::IMessage<TSkill>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TSkill> _parser = new pb::MessageParser<TSkill>(() => new TSkill());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<TSkill> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::RoomProto.ServerprotoReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TSkill() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TSkill(TSkill other) : this() {
      skillType_ = other.skillType_;
      fireAngle_ = other.fireAngle_;
      fireAngleLen_ = other.fireAngleLen_;
      chargeTime_ = other.chargeTime_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TSkill Clone() {
      return new TSkill(this);
    }

    /// <summary>Field number for the "skill_type" field.</summary>
    public const int SkillTypeFieldNumber = 1;
    private long skillType_;
    /// <summary>
    /// 技能类型, 用于唯一确定角色当前释放那个技能
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long SkillType {
      get { return skillType_; }
      set {
        skillType_ = value;
      }
    }

    /// <summary>Field number for the "fire_angle" field.</summary>
    public const int FireAngleFieldNumber = 2;
    private long fireAngle_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long FireAngle {
      get { return fireAngle_; }
      set {
        fireAngle_ = value;
      }
    }

    /// <summary>Field number for the "fire_angle_len" field.</summary>
    public const int FireAngleLenFieldNumber = 3;
    private long fireAngleLen_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long FireAngleLen {
      get { return fireAngleLen_; }
      set {
        fireAngleLen_ = value;
      }
    }

    /// <summary>Field number for the "charge_time" field.</summary>
    public const int ChargeTimeFieldNumber = 4;
    private long chargeTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long ChargeTime {
      get { return chargeTime_; }
      set {
        chargeTime_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as TSkill);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(TSkill other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SkillType != other.SkillType) return false;
      if (FireAngle != other.FireAngle) return false;
      if (FireAngleLen != other.FireAngleLen) return false;
      if (ChargeTime != other.ChargeTime) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (SkillType != 0L) hash ^= SkillType.GetHashCode();
      if (FireAngle != 0L) hash ^= FireAngle.GetHashCode();
      if (FireAngleLen != 0L) hash ^= FireAngleLen.GetHashCode();
      if (ChargeTime != 0L) hash ^= ChargeTime.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SkillType != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(SkillType);
      }
      if (FireAngle != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(FireAngle);
      }
      if (FireAngleLen != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(FireAngleLen);
      }
      if (ChargeTime != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(ChargeTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SkillType != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(SkillType);
      }
      if (FireAngle != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(FireAngle);
      }
      if (FireAngleLen != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(FireAngleLen);
      }
      if (ChargeTime != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(ChargeTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (SkillType != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(SkillType);
      }
      if (FireAngle != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(FireAngle);
      }
      if (FireAngleLen != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(FireAngleLen);
      }
      if (ChargeTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ChargeTime);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(TSkill other) {
      if (other == null) {
        return;
      }
      if (other.SkillType != 0L) {
        SkillType = other.SkillType;
      }
      if (other.FireAngle != 0L) {
        FireAngle = other.FireAngle;
      }
      if (other.FireAngleLen != 0L) {
        FireAngleLen = other.FireAngleLen;
      }
      if (other.ChargeTime != 0L) {
        ChargeTime = other.ChargeTime;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            SkillType = input.ReadInt64();
            break;
          }
          case 16: {
            FireAngle = input.ReadInt64();
            break;
          }
          case 24: {
            FireAngleLen = input.ReadInt64();
            break;
          }
          case 32: {
            ChargeTime = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            SkillType = input.ReadInt64();
            break;
          }
          case 16: {
            FireAngle = input.ReadInt64();
            break;
          }
          case 24: {
            FireAngleLen = input.ReadInt64();
            break;
          }
          case 32: {
            ChargeTime = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class TRoleInfo : pb::IMessage<TRoleInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TRoleInfo> _parser = new pb::MessageParser<TRoleInfo>(() => new TRoleInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<TRoleInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::RoomProto.ServerprotoReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TRoleInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TRoleInfo(TRoleInfo other) : this() {
      roleId_ = other.roleId_;
      level_ = other.level_;
      name_ = other.name_;
      roleConfigId_ = other.roleConfigId_;
      isReady_ = other.isReady_;
      commonSkillId_ = other.commonSkillId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TRoleInfo Clone() {
      return new TRoleInfo(this);
    }

    /// <summary>Field number for the "role_id" field.</summary>
    public const int RoleIdFieldNumber = 1;
    private string roleId_ = "";
    /// <summary>
    /// 角色id(暂时无用)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string RoleId {
      get { return roleId_; }
      set {
        roleId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "level" field.</summary>
    public const int LevelFieldNumber = 2;
    private int level_;
    /// <summary>
    /// 角色等级
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Level {
      get { return level_; }
      set {
        level_ = value;
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 3;
    private string name_ = "";
    /// <summary>
    /// 角色名
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "role_config_id" field.</summary>
    public const int RoleConfigIdFieldNumber = 4;
    private int roleConfigId_;
    /// <summary>
    /// 角色配表id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int RoleConfigId {
      get { return roleConfigId_; }
      set {
        roleConfigId_ = value;
      }
    }

    /// <summary>Field number for the "is_ready" field.</summary>
    public const int IsReadyFieldNumber = 5;
    private bool isReady_;
    /// <summary>
    /// 是否准备就绪
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool IsReady {
      get { return isReady_; }
      set {
        isReady_ = value;
      }
    }

    /// <summary>Field number for the "common_skill_id" field.</summary>
    public const int CommonSkillIdFieldNumber = 6;
    private int commonSkillId_;
    /// <summary>
    /// 选择的召唤师技能
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CommonSkillId {
      get { return commonSkillId_; }
      set {
        commonSkillId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as TRoleInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(TRoleInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RoleId != other.RoleId) return false;
      if (Level != other.Level) return false;
      if (Name != other.Name) return false;
      if (RoleConfigId != other.RoleConfigId) return false;
      if (IsReady != other.IsReady) return false;
      if (CommonSkillId != other.CommonSkillId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (RoleId.Length != 0) hash ^= RoleId.GetHashCode();
      if (Level != 0) hash ^= Level.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (RoleConfigId != 0) hash ^= RoleConfigId.GetHashCode();
      if (IsReady != false) hash ^= IsReady.GetHashCode();
      if (CommonSkillId != 0) hash ^= CommonSkillId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (RoleId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(RoleId);
      }
      if (Level != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Level);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Name);
      }
      if (RoleConfigId != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(RoleConfigId);
      }
      if (IsReady != false) {
        output.WriteRawTag(40);
        output.WriteBool(IsReady);
      }
      if (CommonSkillId != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(CommonSkillId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (RoleId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(RoleId);
      }
      if (Level != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Level);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Name);
      }
      if (RoleConfigId != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(RoleConfigId);
      }
      if (IsReady != false) {
        output.WriteRawTag(40);
        output.WriteBool(IsReady);
      }
      if (CommonSkillId != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(CommonSkillId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (RoleId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RoleId);
      }
      if (Level != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Level);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (RoleConfigId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RoleConfigId);
      }
      if (IsReady != false) {
        size += 1 + 1;
      }
      if (CommonSkillId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CommonSkillId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(TRoleInfo other) {
      if (other == null) {
        return;
      }
      if (other.RoleId.Length != 0) {
        RoleId = other.RoleId;
      }
      if (other.Level != 0) {
        Level = other.Level;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.RoleConfigId != 0) {
        RoleConfigId = other.RoleConfigId;
      }
      if (other.IsReady != false) {
        IsReady = other.IsReady;
      }
      if (other.CommonSkillId != 0) {
        CommonSkillId = other.CommonSkillId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            RoleId = input.ReadString();
            break;
          }
          case 16: {
            Level = input.ReadInt32();
            break;
          }
          case 26: {
            Name = input.ReadString();
            break;
          }
          case 32: {
            RoleConfigId = input.ReadInt32();
            break;
          }
          case 40: {
            IsReady = input.ReadBool();
            break;
          }
          case 48: {
            CommonSkillId = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            RoleId = input.ReadString();
            break;
          }
          case 16: {
            Level = input.ReadInt32();
            break;
          }
          case 26: {
            Name = input.ReadString();
            break;
          }
          case 32: {
            RoleConfigId = input.ReadInt32();
            break;
          }
          case 40: {
            IsReady = input.ReadBool();
            break;
          }
          case 48: {
            CommonSkillId = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// RPG控制命令信息
  /// </summary>
  public sealed partial class TRPGPlayerCmd : pb::IMessage<TRPGPlayerCmd>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TRPGPlayerCmd> _parser = new pb::MessageParser<TRPGPlayerCmd>(() => new TRPGPlayerCmd());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<TRPGPlayerCmd> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::RoomProto.ServerprotoReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TRPGPlayerCmd() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TRPGPlayerCmd(TRPGPlayerCmd other) : this() {
      actorId_ = other.actorId_;
      cmdId_ = other.cmdId_;
      createTime_ = other.createTime_;
      createFrameCount_ = other.createFrameCount_;
      frameCount_ = other.frameCount_;
      cmdIndex_ = other.cmdIndex_;
      skills_ = other.skills_.Clone();
      move_ = other.move_ != null ? other.move_.Clone() : null;
      playerId_ = other.playerId_;
      roleInfo_ = other.roleInfo_ != null ? other.roleInfo_.Clone() : null;
      cmdType_ = other.cmdType_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TRPGPlayerCmd Clone() {
      return new TRPGPlayerCmd(this);
    }

    /// <summary>Field number for the "actor_id" field.</summary>
    public const int ActorIdFieldNumber = 1;
    private string actorId_ = "";
    /// <summary>
    /// 角色id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ActorId {
      get { return actorId_; }
      set {
        actorId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "cmd_id" field.</summary>
    public const int CmdIdFieldNumber = 2;
    private int cmdId_;
    /// <summary>
    /// 命令唯一Id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CmdId {
      get { return cmdId_; }
      set {
        cmdId_ = value;
      }
    }

    /// <summary>Field number for the "create_time" field.</summary>
    public const int CreateTimeFieldNumber = 3;
    private long createTime_;
    /// <summary>
    /// 命令创建时间
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long CreateTime {
      get { return createTime_; }
      set {
        createTime_ = value;
      }
    }

    /// <summary>Field number for the "create_frame_count" field.</summary>
    public const int CreateFrameCountFieldNumber = 4;
    private int createFrameCount_;
    /// <summary>
    /// 命令创建所在帧
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CreateFrameCount {
      get { return createFrameCount_; }
      set {
        createFrameCount_ = value;
      }
    }

    /// <summary>Field number for the "frame_count" field.</summary>
    public const int FrameCountFieldNumber = 5;
    private int frameCount_;
    /// <summary>
    /// 命令实际需要在那一帧执行
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int FrameCount {
      get { return frameCount_; }
      set {
        frameCount_ = value;
      }
    }

    /// <summary>Field number for the "cmd_index" field.</summary>
    public const int CmdIndexFieldNumber = 6;
    private int cmdIndex_;
    /// <summary>
    /// 命令序号
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CmdIndex {
      get { return cmdIndex_; }
      set {
        cmdIndex_ = value;
      }
    }

    /// <summary>Field number for the "skills" field.</summary>
    public const int SkillsFieldNumber = 7;
    private static readonly pb::FieldCodec<global::RoomProto.TSkill> _repeated_skills_codec
        = pb::FieldCodec.ForMessage(58, global::RoomProto.TSkill.Parser);
    private readonly pbc::RepeatedField<global::RoomProto.TSkill> skills_ = new pbc::RepeatedField<global::RoomProto.TSkill>();
    /// <summary>
    /// 释放及的技能列表
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::RoomProto.TSkill> Skills {
      get { return skills_; }
    }

    /// <summary>Field number for the "move" field.</summary>
    public const int MoveFieldNumber = 8;
    private global::RoomProto.TActorMoveInfo move_;
    /// <summary>
    /// 角色移动信息
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::RoomProto.TActorMoveInfo Move {
      get { return move_; }
      set {
        move_ = value;
      }
    }

    /// <summary>Field number for the "player_id" field.</summary>
    public const int PlayerIdFieldNumber = 9;
    private string playerId_ = "";
    /// <summary>
    /// 玩家id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PlayerId {
      get { return playerId_; }
      set {
        playerId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "role_info" field.</summary>
    public const int RoleInfoFieldNumber = 10;
    private global::RoomProto.TRoleInfo roleInfo_;
    /// <summary>
    /// 角色信息
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::RoomProto.TRoleInfo RoleInfo {
      get { return roleInfo_; }
      set {
        roleInfo_ = value;
      }
    }

    /// <summary>Field number for the "cmd_type" field.</summary>
    public const int CmdTypeFieldNumber = 11;
    private int cmdType_;
    /// <summary>
    /// 命令类型
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CmdType {
      get { return cmdType_; }
      set {
        cmdType_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as TRPGPlayerCmd);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(TRPGPlayerCmd other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ActorId != other.ActorId) return false;
      if (CmdId != other.CmdId) return false;
      if (CreateTime != other.CreateTime) return false;
      if (CreateFrameCount != other.CreateFrameCount) return false;
      if (FrameCount != other.FrameCount) return false;
      if (CmdIndex != other.CmdIndex) return false;
      if(!skills_.Equals(other.skills_)) return false;
      if (!object.Equals(Move, other.Move)) return false;
      if (PlayerId != other.PlayerId) return false;
      if (!object.Equals(RoleInfo, other.RoleInfo)) return false;
      if (CmdType != other.CmdType) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ActorId.Length != 0) hash ^= ActorId.GetHashCode();
      if (CmdId != 0) hash ^= CmdId.GetHashCode();
      if (CreateTime != 0L) hash ^= CreateTime.GetHashCode();
      if (CreateFrameCount != 0) hash ^= CreateFrameCount.GetHashCode();
      if (FrameCount != 0) hash ^= FrameCount.GetHashCode();
      if (CmdIndex != 0) hash ^= CmdIndex.GetHashCode();
      hash ^= skills_.GetHashCode();
      if (move_ != null) hash ^= Move.GetHashCode();
      if (PlayerId.Length != 0) hash ^= PlayerId.GetHashCode();
      if (roleInfo_ != null) hash ^= RoleInfo.GetHashCode();
      if (CmdType != 0) hash ^= CmdType.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ActorId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ActorId);
      }
      if (CmdId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(CmdId);
      }
      if (CreateTime != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(CreateTime);
      }
      if (CreateFrameCount != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(CreateFrameCount);
      }
      if (FrameCount != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(FrameCount);
      }
      if (CmdIndex != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(CmdIndex);
      }
      skills_.WriteTo(output, _repeated_skills_codec);
      if (move_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(Move);
      }
      if (PlayerId.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(PlayerId);
      }
      if (roleInfo_ != null) {
        output.WriteRawTag(82);
        output.WriteMessage(RoleInfo);
      }
      if (CmdType != 0) {
        output.WriteRawTag(88);
        output.WriteInt32(CmdType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ActorId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ActorId);
      }
      if (CmdId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(CmdId);
      }
      if (CreateTime != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(CreateTime);
      }
      if (CreateFrameCount != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(CreateFrameCount);
      }
      if (FrameCount != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(FrameCount);
      }
      if (CmdIndex != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(CmdIndex);
      }
      skills_.WriteTo(ref output, _repeated_skills_codec);
      if (move_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(Move);
      }
      if (PlayerId.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(PlayerId);
      }
      if (roleInfo_ != null) {
        output.WriteRawTag(82);
        output.WriteMessage(RoleInfo);
      }
      if (CmdType != 0) {
        output.WriteRawTag(88);
        output.WriteInt32(CmdType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ActorId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ActorId);
      }
      if (CmdId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CmdId);
      }
      if (CreateTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(CreateTime);
      }
      if (CreateFrameCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CreateFrameCount);
      }
      if (FrameCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(FrameCount);
      }
      if (CmdIndex != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CmdIndex);
      }
      size += skills_.CalculateSize(_repeated_skills_codec);
      if (move_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Move);
      }
      if (PlayerId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PlayerId);
      }
      if (roleInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RoleInfo);
      }
      if (CmdType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CmdType);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(TRPGPlayerCmd other) {
      if (other == null) {
        return;
      }
      if (other.ActorId.Length != 0) {
        ActorId = other.ActorId;
      }
      if (other.CmdId != 0) {
        CmdId = other.CmdId;
      }
      if (other.CreateTime != 0L) {
        CreateTime = other.CreateTime;
      }
      if (other.CreateFrameCount != 0) {
        CreateFrameCount = other.CreateFrameCount;
      }
      if (other.FrameCount != 0) {
        FrameCount = other.FrameCount;
      }
      if (other.CmdIndex != 0) {
        CmdIndex = other.CmdIndex;
      }
      skills_.Add(other.skills_);
      if (other.move_ != null) {
        if (move_ == null) {
          Move = new global::RoomProto.TActorMoveInfo();
        }
        Move.MergeFrom(other.Move);
      }
      if (other.PlayerId.Length != 0) {
        PlayerId = other.PlayerId;
      }
      if (other.roleInfo_ != null) {
        if (roleInfo_ == null) {
          RoleInfo = new global::RoomProto.TRoleInfo();
        }
        RoleInfo.MergeFrom(other.RoleInfo);
      }
      if (other.CmdType != 0) {
        CmdType = other.CmdType;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ActorId = input.ReadString();
            break;
          }
          case 16: {
            CmdId = input.ReadInt32();
            break;
          }
          case 24: {
            CreateTime = input.ReadInt64();
            break;
          }
          case 32: {
            CreateFrameCount = input.ReadInt32();
            break;
          }
          case 40: {
            FrameCount = input.ReadInt32();
            break;
          }
          case 48: {
            CmdIndex = input.ReadInt32();
            break;
          }
          case 58: {
            skills_.AddEntriesFrom(input, _repeated_skills_codec);
            break;
          }
          case 66: {
            if (move_ == null) {
              Move = new global::RoomProto.TActorMoveInfo();
            }
            input.ReadMessage(Move);
            break;
          }
          case 74: {
            PlayerId = input.ReadString();
            break;
          }
          case 82: {
            if (roleInfo_ == null) {
              RoleInfo = new global::RoomProto.TRoleInfo();
            }
            input.ReadMessage(RoleInfo);
            break;
          }
          case 88: {
            CmdType = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ActorId = input.ReadString();
            break;
          }
          case 16: {
            CmdId = input.ReadInt32();
            break;
          }
          case 24: {
            CreateTime = input.ReadInt64();
            break;
          }
          case 32: {
            CreateFrameCount = input.ReadInt32();
            break;
          }
          case 40: {
            FrameCount = input.ReadInt32();
            break;
          }
          case 48: {
            CmdIndex = input.ReadInt32();
            break;
          }
          case 58: {
            skills_.AddEntriesFrom(ref input, _repeated_skills_codec);
            break;
          }
          case 66: {
            if (move_ == null) {
              Move = new global::RoomProto.TActorMoveInfo();
            }
            input.ReadMessage(Move);
            break;
          }
          case 74: {
            PlayerId = input.ReadString();
            break;
          }
          case 82: {
            if (roleInfo_ == null) {
              RoleInfo = new global::RoomProto.TRoleInfo();
            }
            input.ReadMessage(RoleInfo);
            break;
          }
          case 88: {
            CmdType = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
